ALTER TABLE users ADD COLUMN is_banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN verification_badge VARCHAR(50) NOT NULL DEFAULT 'NONE';
ALTER TABLE users ADD COLUMN profile_image_url VARCHAR(500);
