ALTER TABLE matches RENAME COLUMN requirement_id TO artisan_requirement_id;

ALTER TABLE matches ADD COLUMN donor_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE matches ALTER COLUMN donor_id DROP DEFAULT;
ALTER TABLE matches ADD CONSTRAINT fk_matches_donor FOREIGN KEY (donor_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE matches ADD COLUMN artisan_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE matches ALTER COLUMN artisan_id DROP DEFAULT;
ALTER TABLE matches ADD CONSTRAINT fk_matches_artisan FOREIGN KEY (artisan_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE matches ALTER COLUMN match_score TYPE DOUBLE PRECISION;

ALTER TABLE matches ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE matches ADD CONSTRAINT uc_matches_donation_requirement UNIQUE (donation_id, artisan_requirement_id);
